#! /bin/bash
for kasutaja in $(sed -n '1p' kasutajanimed)
	do useradd $kasutaja
	done
for kasutaja2 in $(sed -n '2p' kasutajanimed)
	do useradd $kasutaja2
        done
for kasutaja3 in $(sed -n '3p' kasutajanimed)
        do useradd $kasutaja3
        done
tail -3 /etc/passwd

